### PR TITLE
cool changes

### PR DESCRIPTION
**Pull request by canedoly**
- Added "forward" yaw so you can have legit aa
- Fixed colorpickers overlapping for hitbox matrix and make colors not have 0 alpha

### CODE REVIEW

**Comment by johnathon-walnut** [comment]
Does the forward fake yaw actually work? Surely you'd just be spazzing all over?

**Comment by canedoly** [comment]
I wasn't home, everything should be fine except when you select real none and fake forward then it jitters like 25 degrees

**Review by johnathon-walnut — CHANGES_REQUESTED** [review]
Please make the vars you added save

**Comment by johnathon-walnut** [comment]
> Please make the vars you added save

and load

**Comment by canedoly** [comment]
I didn't make new vars I only changed them + I just checked and they load and save fine

**Comment by johnathon-walnut** [comment]
fairs, ill merge then

**Comment by johnathon-walnut** [comment]
monkey brain saw green in vars.h

**Pull request merged**
