### PR TITLE
minor changes

### PR DESCRIPTION
**Pull request by canedoly**
- made the name esp white, it just looks better
- added color picker and a toggle for movement simulation prediction line

### CODE REVIEW

**Comment by johnathon-walnut** [comment]
I disagree with white name esp, make it an option

**Comment by johnathon-walnut** [comment]
And yes I know this is hypocritical given the changes I did to condition ESP.

**Comment by canedoly** [comment]
I could make the white name esp an option only, i'm guessing it would be simple

**Comment by wsock** [comment]
Don't add random color changing shit, people can do it on their own and it just clogs the code

**Comment by johnathon-walnut** [comment]
More customization built-in is usually a better thing in my opinion.

**Comment by canedoly** [comment]
so do I make a var to change between drawcolor and white or a color picker insead of white is better?

**Comment by wsock** [comment]
colorpickers are better than hardcoded colors.

**Comment by canedoly** [comment]
okay will do

**Pull request closed without merging**
