### PR TITLE
Added splash prediction

### PR DESCRIPTION
**Pull request by lnx00**
Added splash prediction to the projectile aimbot that will try to deal splash damage if no target could be found.
[Preview](https://streamable.com/nj63i2)

Other changes:
- Added a warning when tf2 is using dxlevel <90
- Player priority fix

### CODE REVIEW

**Comment by SylveonBottle** [comment]
Dope, looks great for cheesing bots. Does it predict enemy movement for pre-firing splash damage?

**Comment by lnx00** [comment]
> Dope, looks great for cheesing bots. Does it predict enemy movement for pre-firing splash damage?

No, it does not predict movement. The intention of this feature was to attack enemies that are hiding behind corners etc.

I think that movement prediction wouldn't make sense here, since we could simply target the enemy directly if they're already moving into our view.

**Comment by xxmyn** [comment]
of course I tested this before merging!

**Comment by SylveonBottle** [comment]
Is it possible to incorporate something like [cathook's auto viewmodel flipper](https://github.com/nullworks/cathook/blob/master/src/hacks/AutoViewmodel.cpp)?


https://user-images.githubusercontent.com/17802843/169708107-1ff80221-2dc5-43c5-b2b8-42ead37147ef.mp4

With that in mind, it should be possible to aim a little closer if we're firing from the left side of the screen.

**Comment by johnathon-walnut** [comment]
could be very interesting lol

**Comment by johnathon-walnut** [comment]
i've seen clips of it going spaz mode on cathook

**Comment by lnx00** [comment]
That's actually a good idea

**Comment by SylveonBottle** [comment]
Also, it seems like splash prediction is ignoring aimbot FOV?
I'm randomly shooting off to my left/right whenever holding aimkey but not looking at anyone in FOV

**Comment by johnathon-walnut** [comment]
sigma

**Comment by SylveonBottle** [comment]
also this

https://user-images.githubusercontent.com/17802843/169710413-24bd0175-4514-4c7f-ba5a-ee345755cde0.mp4

**Comment by gayblackirony** [comment]
wallbang

**Comment by johnathon-walnut** [comment]
intended feature obviously

**Comment by lnx00** [comment]
uhh it seems that i forgot to check if the enemy can even receive splash damage from the predicted location. Should be easily fixable by casting a trace

**Comment by johnathon-walnut** [comment]
hey lnx

**Comment by johnathon-walnut** [comment]
look at how the uh

**Comment by johnathon-walnut** [comment]
demoman triggerbot works

**Comment by lnx00** [comment]
i will

**Comment by lnx00** [comment]
I have added a viewmodel flipper to improve the accuracy:
https://streamable.com/e6x16o

**Comment by lnx00** [comment]
Alright, i've fixed everything you mentioned about the splash prediction.
It will be added in my next PR

**Pull request merged**
