### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by lnx00**
- Added cleaver to projectile aimbot (this does seem to work most of the time)
- Some menu improvements
- Added more help markers to the menu

### CODE REVIEW

**Comment by bruisfat** [comment]
Is there a way to save my configs because I might be blind.

**Comment by lnx00** [comment]
> Is there a way to save my configs because I might be blind.

Yes, right click on the menu bar.

**Comment by bruisfat** [comment]
thank you

**Comment by tf2cheater2013** [comment]
THIS LOOKS FUCKING P

**Comment by M-F3D** [comment]
goodbye commented out old menu

**Pull request merged**
