### PR TITLE
Added Auto Peek, Party ESP and more

### PR DESCRIPTION
**Pull request by lnx00**
Always got bored while playing HVH? Then fear no more!

- Added Auto Peek: Automatically peeks in a given direction as soon as an enemy is visible
- Added Party ESP: Sends nearby player positions to other party members (Far ESP)
- Fixed party markers
- Code cleanup

Auto Peek isn't perfect, but it works surprisingly well.

### CODE REVIEW

**Comment by wayven** [comment]
wow time to criticize it heavily!

**Comment by tf2cheater2013** [comment]
dead projekt lel

**Comment by xxmyn** [comment]
i forgor to merge

**Comment by johnathon-walnut** [comment]
Very nicely done, thanks

**Pull request merged**
