### PR TITLE
Improved Anti-Aim

### PR DESCRIPTION
**Pull request by lnx00**
- Added "No Overlap" option, that prevents the real and fake angles from overlapping
- Added interval option for random AA
- Added "On Hurt" AA mode that picks a random yaw when someone hits you
- Small fixes

### CODE REVIEW

**Comment by xxmyn** [comment]
i hope you have sufficiently tested this and know that each of these features works as advertised after extensive testing and havent just pasted random code in and not done any actual checks.

if so, ty for commit, will merge and then test when i get home

**Comment by lnx00** [comment]
I did try everything i've added (as I always do) and this code is completely selfmade.

My code has never caused anything to break in the past, if that's what you're up to.

**Comment by xxmyn** [comment]
i dont understand how avoid overlap actually stops ur fake and real from overlapping, it looks like it just changes your angles when they overlap, but we dont have accurate fake angle shit, like even with leg jitter the anti aim isnt that great.

if it does stop ur serverside fake from overlapping thats still kind of cool ig

**Comment by lnx00** [comment]
That's correct. When your angles are about to overlap, it will simply change your real yaw +/-50 to prevent it. I thought that it's still better than nothing

**Comment by xxmyn** [comment]
im wondering if its possible to just look at our local players networked angles and positions...

**Pull request merged**
