### PR TITLE
poopy poo mouse extermination

### PR DESCRIPTION
**Pull request by AscendedSion**
cy alosetr

### CODE REVIEW

**Comment by M-F3D** [comment]
theres another PR coming i think that will add tooltips and also remove this so idk if i should merge or not because it might make conflicts and those are never fun to resolve

**Comment by AscendedSion** [comment]
hmmm

**Comment by lnx00** [comment]
I have already done this in my branch:
https://github.com/lnx00/Fedoraware/tree/fix-1

Will commit as soon as I'm done with everything menu related

**Comment by AscendedSion** [comment]
awesome epic.

**Pull request closed without merging**
