### PR TITLE
Pog update

### PR DESCRIPTION
**Pull request by lnx00**
- Added -insecure toggle to debug menu (can not be used to change the state, it's more of an indicator)
- Added BytePatch utilities and a manager for them _(Hooks/PatchManager)_
- Added viewmodel flipper to shoot around edges (only works with an active aimbot target)
- Improved splash prediction
- Added and then removed fake latency :trollface: 

Thanks to @SylveonBottle for providing actual issues and suggestions.

### CODE REVIEW

**Comment by SylveonBottle** [comment]
Splash prediction seems to still ignore aimbot FOV, resulting in you randomly shooting rockets behind you.

**Comment by lnx00** [comment]
It does indeed ignore aimbot FOV because i don't use FOV for projectile aimbot lol
But i can add it

**Comment by lnx00** [comment]
> Splash prediction seems to still ignore aimbot FOV, resulting in you randomly shooting rockets behind you.

How would you want to aimbot to behave? Should it check if the player is in your FOV or if the predicted splash location is in your FOV?

**Comment by SylveonBottle** [comment]
> How would you want to aimbot to behave? Should it check if the player is in your FOV or if the predicted splash location is in your FOV?

Personally, having a switch between the two would be great.
But if I was limited to one option, the predicted splash location of course, since that's where it'll be aiming. Aim FOV is to prevent you from shooting outside of the fov.

**Comment by johnathon-walnut** [comment]
yeah we should have a really non ambiguously named dropdown for trailing/leading :trollface:

**Comment by lnx00** [comment]
Fixed in #313

**Pull request merged**
