### PR TITLE
Huntsman Prediction

### PR DESCRIPTION
**Pull request by hivec2**
Maybe switch your correct values for my bruteforced values :)
https://youtu.be/0SUeCQZtRL0

### CODE REVIEW

**Comment by lnx00** [comment]
What did even happen to the projectile aimbot? It used to work perfectly fine on the huntsman iirc

**Comment by johnathon-walnut** [comment]
tell me the song

**Comment by johnathon-walnut** [comment]
I want the song i'll merge if i get the song

**Comment by lnx00** [comment]
https://www.youtube.com/watch?v=s9JfhYaiHAA

10 seconds google search

**Comment by johnathon-walnut** [comment]
thanks

**Pull request merged**
